name = "GeothermalWells"
uuid = "9e50befb-bb92-4f5a-8f9f-381c571c0866"
version = "0.1.1"
authors = ["Collin Wittenstein <collin.wittenstein@gmail.com>"]

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
OrdinaryDiffEqStabilizedRK = "358294b1-0aab-51c3-aafe-ad5ab194a2ad"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Adapt = "4.4.0"
DelimitedFiles = "1.9.1"
DiffEqBase = "6.199.0"
DiffEqCallbacks = "4.12.0"
JLD2 = "0.6.3"
KernelAbstractions = "0.9.39"
MuladdMacro = "0.2.4"
OrdinaryDiffEqStabilizedRK = "1.8.0"
Plots = "1.41.4"
julia = "1.12"
